//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestsAspNet5Test {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class UnitTestsAspNet5 : global::System.Configuration.ApplicationSettingsBase {
        
        private static UnitTestsAspNet5 defaultInstance = ((UnitTestsAspNet5)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UnitTestsAspNet5())));
        
        public static UnitTestsAspNet5 Default {
            get {
                return defaultInstance;
            }
        }
    }
}
